@startuml

start

: 1. C Retrieve Self Information Document SID from P;
: 2. C Parse SID for description of offered Resources by P;
: 3. From resource descriptions, C select resource of interest R;
: 4. C Check contract offered by P for R;

if (Contract specified by P?) then (yes)
    if (Contract acceptable for C?) then (no)
        :5. C negotiate Contract with P;

        if (Negotiation successful?) then (yes)
            else (no)
                stop
        endif
    endif
endif

if (6. Operations specified for R?) then (no)

    if (7. Endpoints specified for R?) then (no)
        :8. C access R outside of IDS;
        stop
    else (yes)
        :9. Select and Invoke Endpoint;
        :10. C Retrieve Data;
        stop
    endif

    else (yes)
endif

: 11. C Check Operations provided by the interfaces;
: 12. C Select operation of interest O;

if (Custom Protocol Binding specified by P?) then (yes)
    : 12a. C invoke O based on Protocol Binding;

    else (no)
    :12b. C invoke O using IDS messaging type(s);
endif

: 13. C retrieve operation Result (Data);

stop

@enduml