@startuml

hide footbox

participant "**Consumer**\n(IDS Connector)" as C
participant "**Provider**\n(IDS Connector)" as P
participant "Provider-internal Contract Service" as PCS

== Authorized Connection Established ==

note right of C: *Reference to base contract C\n* Suggested contract C' as payload
C -> P: 1a. ContractRequestMessage

C <-- P: 1b. RequestInProcessMessage

note right of P: C'
P -> PCS: 2a. contract acceptable?
P <-- PCS: 2b. acceptance verification result

note left of P: Alternative Contract C''
P --> C: 3. ContractOfferMessage

note right of C: Agreed contract C'' as payload
C --> P: 4a. ContractAgreement
P --> C: 4b. ContractAgreement

@enduml
