@startuml

hide footbox

participant "**Consumer**\n(IDS Connector)" as C
participant "**Provider**\n(IDS Connector)" as P
participant "Provider Authorization Service" as PAS
participant "Provider Data Service" as PDS

== Authenticated Connection Established ==

note right of C: optional: Dynamic Attribute Token
C -> PAS: 1a. request access token

note left of PAS: Access Token
PAS --> C: 1b. issue token

== Authorized Connection Established ==

group Resource Usage

C <-> PDS: 2ff. //resource transfer, query, transformation, etc.//

end

@enduml
