@startuml

hide footbox

participant "**Consumer**\n(IDS Connector)" as C
participant "**Provider**\n(IDS Connector)" as P
participant "Provider-internal Identity\nand Access Management" as PAS
participant "Provider Data Service" as PDS

== Secure Connection Established ==

C -> P: 1a. AccessTokenRequest

P -> PAS: delegate request
P <-- PAS: issued token

P --> C: 1b. AccessTokenResponse

== Authorized Session Established ==

group Resource Usage

C <-> PDS: 2ff. //resource transfer, query, transformation, etc.//

end

@enduml
