@startuml

start

fork
:Participant Certification;
fork again
:Core Component Certification;
end fork

partition "Content Exchange Setup" {
	:Create Self-Information;
	:Setup Data Retrieval Methods;
	:Deploy locally;
}

partition "Security Setup" {
    :Deploy X.590 Certificate;
    :Register and Setup DAPS and SOC;
}

partition "Availability Setup" {
    :Ensure IDS-wide Reachability;
    :Register at Broker;
}

stop

@enduml