@startuml

start

title Stage 0: Setup

fork
:Participant Certification;
fork again
:Core Component Certification;
end fork

partition "Content Exchange Setup" {
	:Create Self-Information;
	:Setup Data Endpoints;
	:Deploy Internally;
}

partition "Security Setup" {
    :Deploy X.590 Certificate;

    if (Use IDSCP?) then (yes)
        :Register and Setup DAPS and SOC;
    endif
}

partition "Availability Setup" {
    :Ensure IDS-wide Reachability;
    :Register at Broker;
}

stop

@enduml