@startuml

start

if (Connector known?) then (no)
    :Query Broker;
else (yes)
    :Retrieve Self Information;
endif

:Verify Self Information;

if (verification successful?) then (yes)
    else (no)
        stop
endif

:Technical Preparation;
:Content Negotiation;

stop

@enduml